// <auto-generated />
using System;
using ExchangeRateManagerAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExchangeRateManagerAPI.Migrations
{
    [DbContext(typeof(CryptoTaxManDbContext))]
    [Migration("20240911034304_TradingPair updates")]
    partial class TradingPairupdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.CryptoUserTransaction", b =>
                {
                    b.Property<int>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Sequence"));

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AmountAssetType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ExchangeRateCurrency")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ExchangeRateValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsNFT")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReportableAsIncome")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReviewRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TaxableEvent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UsesManualAssignedExchangeRate")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ValueAssetType")
                        .HasColumnType("longtext");

                    b.HasKey("Sequence", "TransactionType");

                    b.HasIndex("Amount")
                        .HasDatabaseName("Idx_Amount");

                    b.HasIndex("AmountAssetType")
                        .HasDatabaseName("Idx_AmountAssetType");

                    b.HasIndex("Sequence")
                        .HasDatabaseName("Idx_Sequence");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("Idx_TransactionDate");

                    b.HasIndex("TransactionType")
                        .HasDatabaseName("Idx_TransactionType");

                    b.HasIndex("TransactionDate", "AmountAssetType")
                        .HasDatabaseName("Idx_TransactionDateAndAmountAssetType");

                    b.ToTable("CryptoUserTransactions", (string)null);
                });

            modelBuilder.Entity("Shared.Models.CryptoUserTransactionStaging", b =>
                {
                    b.Property<int>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Sequence"));

                    b.Property<decimal?>("AmountIn")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AmountOut")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CurrencyIn")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CurrencyOut")
                        .HasColumnType("longtext");

                    b.Property<string>("ExchangeCurrency")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("FeeCurrency")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsProcessed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<bool?>("ReportableAsIncome")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TransactionEvent")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Sequence");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("Idx_IsProcessed_Staging");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("Idx_TransactionDate_Staging");

                    b.HasIndex("TransactionDate", "CurrencyIn")
                        .HasDatabaseName("Idx_TransactionDateAndCurrencyIn_Staging");

                    b.ToTable("CryptoUserTransactionsStaging", (string)null);
                });

            modelBuilder.Entity("Shared.Models.ExchangeRate", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Symbol")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExchangeCurrency")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DataSource")
                        .HasColumnType("longtext");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("LookupOptional")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("LowHighAverage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("LowHighPercentageDifference")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OpenCloseAverage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OpenClosePercentageDifference")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Date", "Symbol", "ExchangeCurrency");

                    b.HasIndex("Date")
                        .HasDatabaseName("Idx_Date");

                    b.HasIndex("ExchangeCurrency")
                        .HasDatabaseName("Idx_ExchangeCurrency");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("Idx_Symbol");

                    b.ToTable("ExchangeRates", (string)null);
                });

            modelBuilder.Entity("Shared.Models.TradingPairInformation", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExchangeCurrency")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExchangeName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExchangeSymbol")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kind")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastExchangeRateEntryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastSyncStatus")
                        .HasColumnType("longtext");

                    b.Property<bool>("SyncError")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("SyncedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Symbol", "ExchangeCurrency", "ExchangeName");

                    b.HasIndex("ExchangeCurrency")
                        .HasDatabaseName("Idx_ExchangeCurrency");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("Idx_IsActive");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("Idx_Symbol");

                    b.ToTable("TradingPairInformation", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
